#!/usr/bin/env python

import git
import logging
import os.path
import sys

import cpthook


def parse_options():
    import optparse
    parser = optparse.OptionParser()
    parser.add_option("-c", "--config", dest="config_file", metavar="FILE",
                      default="hook.cfg", help="cpthook config file")
    parser.add_option("-v", "--verbose", dest="verbose", default=False,
                      action="store_true",
                      help="log verbose status information")
    parser.add_option("-d", "--debug", dest="debug", default=False,
                      action="store_true",
                      help="log debug information")
    parser.add_option("--dry-run", dest="dryrun", default=False,
                      action="store_true",
                      help="perform a dry run, making no changes")
    parser.add_option("--init", dest="init", default=False,
                      action="store_true",
                      help="install configured hooks and repositories")
    parser.add_option("--hook", dest="hook", default=None,
                      help="the hook to run against the current repository")
    options, args = parser.parse_args()
    return options, args


def validate_options(opts):
    if not os.path.isfile(opts.config_file):
        print 'No config file "{0}"'.format(opts.config_file)
        sys.exit(-1)

    if opts.init and opts.hook:
        print 'Cannot install to repos and be invoked as a hook'
        sys.exit(-1)

    if opts.hook is not None and opts.hook not in cpthook.supported_hooks:
        print 'Unsupported hook "{0}"'.format(opts.hook)
        sys.exit(-1)


def handle_options():
    opts, args = parse_options()
    validate_options(opts)

    if opts.debug:
        log_level = logging.DEBUG
    elif opts.verbose:
        log_level = logging.INFO
    else:
        log_level = logging.WARN
    logging.getLogger().setLevel(log_level)

    return opts, args


def install_hooks(config, opts):
    pass


def run_hook(hook, config, opts, args):
    try:
        repo = git.Repo('.')
    except git.errors.InvalidGitRepositoryError:
        print '{0} is not a git repo?'.format(
            os.path.realpath(os.path.curdir))
        sys.exit(-1)
    pass


if __name__ == '__main__':
    # Any positional args returned by optparse are intended for
    # the hook script to be invoked.
    opts, hook_args = handle_options()
    config = cpthook.CptHookConfig(opts.config_file)

    if opts.init:
        # Install cpthook wrapper to configured repositories
        logging.info('Installing cpthook wrapper to repositories')
        install_hooks(config)
    elif opts.hook:
        # Run requested hook on repository
        logging.info('Running {0} hooks'.format(opts.hook))
        run_hook(opts.hook, config, opts, hook_args)
    else:
        logging.debug('No command given.')
        print 'Use --help for assistance'
